import type { Metadata } from "next";
import { Bodoni_Moda } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "./providers";


const bodoniModa = Bodoni_Moda({ subsets: ["latin"],
  weight: ['400', '700'], // Specify the weights you need
  variable: '--font-bodoni-moda', // Optional: Define a CSS variable
});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bodoniModa.variable}>
      <Providers>
      <Header/>
        {children}
        <Footer/>
        </Providers>
        </body>
    </html>
  );
}
